#####################################
# Monochrome theme for kitty        #
#####################################
## name:     Monochrome
## author:   MHIA
## license:  IDK

# The basic colors
foreground              #bbb49d
background              #1e2224
selection_foreground    #1e2224
selection_background    #bbb49d

# Cursor colors
cursor                  #ece6d9
cursor_text_color       #1e2224

# URL underline color when hovering with mouse
url_color               #bbb49d

# Kitty window border colors
active_border_color     #bbb49d
inactive_border_color   #49504f
bell_border_color       #ece6d9

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #1e2224
active_tab_background   #bbb49d
inactive_tab_foreground #85867a
inactive_tab_background #49504f
tab_bar_background      #1e2224

# Colors for marks (marked text in the terminal)
mark1_foreground #1e2224
mark1_background #bbb49d
mark2_foreground #1e2224
mark2_background #ece6d9
mark3_foreground #1e2224
mark3_background #85867a

# The 16 terminal colors
# black
color0  #1e2224
color8  #49504f

# red
color1  #636862
color9  #85867a

# green
color2  #85867a
color10 #bbb49d

# yellow
color3  #bbb49d
color11 #ece6d9

# blue
color4  #636862
color12 #85867a

# magenta
color5  #85867a
color13 #ece6d9

# cyan
color6  #bbb49d
color14 #ece6d9

# white
color7  #bbb49d
color15 #ffffff
